[FEAT] 커스텀 전역 예외처리
Trip-Record/Server pull request #15
Opened 2024-01-14 13:17 UTC by muncool39

## Related Issue

- feat/#6 -> dev
- close #6

## Key Changes

- 예외 발생시의 return 값을 커스텀했습니다.
예외를 발생시킬 상황에 커스텀 오류를 알맞은 ERROR_CODE와 함께 던집니다.
```java
if (user.isPresent()) {
        throw new TripRecordException(ErrorCode.DUPLICATE_EMAIL);
}
```
![image](https://github.com/Trip-Record/Server/assets/105481797/178a99ee-b2b2-4ba4-93a4-5048bddbdd8f)

- request 객체가 검증되도록 했습니다.
필수 데이터가 모두 입력되지 않았을 경우, 다음과 같은 결과가 반환됩니다.
![image](https://github.com/Trip-Record/Server/assets/105481797/07b4a4be-4c54-4d8b-9f78-e8fcf2f38bf8)

## To Reviewers

- dto class에서는 `@NotNull` , controller class 에는 `@Valid`를 사용하면 데이터가 들어오지 않은 경우 예외를 발생시킵니다.
- 예외를 발생시킬 때에는 TripRecordException를 던지고 인자로 에러 코드를 전달하면 됩니다.
- ErrorCode enum 클래스에는 return 되는 httpStatus가 정의됩니다.
필요한 상황이 있을 때마다 각자 에러코드를 정의해서 활용하면 됩니다.
ex) `RECORD_NOT_FOUND(HttpStatus.NOT_FOUND,"기록 정보를 찾을 수 없습니다.")`

앞으로 구현할 때 해당 내용을 활용해 개발을 진행하면 될 것 같습니다! 😃

2024-01-14 13:46 UTC, gitseoyeon approved these changes
확인 했습니다!! 혹시나 구현하다가 나중에 여쭤볼 사항 생기게 되면 따로 여쭤보도록 하겠습니다!!

2024-01-14 15:44 UTC, ChaeAg requested changes
고생했습니다~~ 너무 잘 해주셨네요~~

2024-01-14 15:44 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/global/exception/ErrorCode.java
> +
혹시 요 공백 의미가 없다면 없애주실 수 있나용?

2024-01-14 15:44 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/user/UserController.java
> +    public ResponseEntity<?> login(@RequestBody @Valid UserLoginRequest userLoginRequest) {
리턴값을 ResponseEntity<Map<String, String>>으로 변경해주실 수 있을까요?

2024-01-14 15:44 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/global/exception/GlobalControllerAdvice.java
> +        return ResponseEntity.badRequest().body(new ExceptionDTO("unexpected runtime exception"));
혹시 이 RuntimeException 예외도 '예상치 못한 런타임 예외입니다.' 와 같은 한글 메세지로 나타내주실 수 있을까용?

2024-01-14 15:44 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/user/UserCreateRequest.java
> +        @Email String userEmail,
여기서 쓰인 이메일의 형식을 검사하는 어노테이션인 @Email은 검사가 살짝 허술하다고 합니다.
@ <- 해당 문자가 들어가면 무조건 true를 뱉으며, null 또한 검사하지 않는다고 합니다.
그래서 아래와 같은 방법을 제안드려요.
1. @Email 어노테이션과 @NotNull 어노테이션을 함께 쓴다.
2. 정규식을 통해 검사한다.
```java
@NotNull
@Pattern(regexp="^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])+[.][a-zA-Z]{2,3}$")
String userEmail
```

2024-01-15 03:41 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/user/UserController.java
> +    public ResponseEntity<?> login(@RequestBody @Valid UserLoginRequest userLoginRequest) {
예외처리랑은 연관이 없는 내용이라는 생각이 들어서 
후에 담당자가 따로 리팩토링을 진행해도 괜찮을 것 같다 생각해 건들지 않았습니다😅
짧은 내용이니 그냥 함께 수정하겠습니다 !

2024-01-15 03:43 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/user/UserCreateRequest.java
> +        @Email String userEmail,
좋네요! 👍 수정하겠습니다~

2024-01-15 03:43 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/global/exception/ErrorCode.java
> +
확인했습니다!

2024-01-15 03:54 UTC, muncool39 commented
리뷰를 반영해 수정했습니다 !

2024-01-16 16:41 UTC, ChaeAg approved these changes
굿입니다~ 수고 많으셨어요!!
👍👍

2024-01-16 16:51 UTC, merged