[FEAT] 일정 생성 API 구현
Trip-Record/Server pull request #24
Opened 2024-01-23 18:13 UTC by ChaeAg

## Related Issue

- feat/#23 -> dev
- close #23

## Key Changes

일정 관련 정보를 받아서 일정, 세부 일정, 일정장소를 생성하는 API를 구현했습니다.
일정 안에 존재하는 세부 일정은 일정의 시작일부터 마지막일까지 존재하지만, 세부 일정 내용을 작성하지 않은 일자는 DB에는 저장하지 않음으로써 작성하지 않은 세부 일정으로 취급합니다.

해당 API의 로직은 다음과 같습니다.
> 1. 일정 정보들을 받아온다.
> 2. 헤더의 유저 토큰으로 유저 정보를 알아낸다. (없으면 에러 발생)
> 3. 받아온 일정 장소들(1~3개)이 DB에 존재하는지 확인한다. (없으면 에러 발생)
> 4. 일정의 시작일과 종료일이 올바른지 확인한다. (올바르지 않으면 에러 발생)
> 5. 일정을 DB에 저장한다.
> 6. 일정 장소를 DB에 저장한다.
> 7. 세부 일정이 있는지 확인 후, 있다면 세부 일정의 일자가 큰 일정의 기간에 속하는지 검사한다. (아닐 시 에러 발생)
> 8. 세부 일정을 DB에 저장한다.

<br>

DTO 내부에 또 다른 DTO를 사용할 때, 내부 DTO의 검증은 @Valid 어노테이션을 사용했습니다.
```java
public record ScheduleCreateRequest(
        ...
        @Valid @NotNull List<ScheduleDetailCreateRequest> scheduleDetails
) {
}
``` 

## To Reviewers

일정 생성의 주의 깊게 보면 좋을 예외처리는 다음과 같습니다. (이 외 다른 예외처리도 있습니다!)
1. _일정 제목이 빈 문자열인가?_
2. _일정 장소가 1~3개 선택되었는가?_
3. _세부 일정 내용이 빈 문자열인가?_
4. _일정 종료일이 시작일 후인가?_
5. _세부 일정 일자가 일정 시작일~종료일 사이인가?_

생각나는대로 예외처리를 하긴 했는데, 어디까지 예외처리를 해야할지 잘 감이 안오네용,,!
혹시 추가해야 할 예외나 다른 부분에서 궁금한점, 수정할 점이 있다면 말씀주세요!!

## References

X

2024-01-24 01:43 UTC, muncool39 requested changes
날짜 처리가 까다로워 보였는데, 예외처리나 구현을 너무 잘 하신 것 같습니다! 👍
- createSchedule 이라는 한 메소드에서 많은 일을 처리하고 있다고 생각이 들어서, 이 부분을 수정하면 더 좋을 것 같습니다!
- #21 관련 메서드가 포함되어 있는데, 해당 내용은 이후 담당자가 수정하면 될 것 같습니다.
- 저도 그렇고 현재 response를 보낼 때 `message:내용` 형태의 Map을 만들어 보냈는데, 이 부분은 공통으로 사용할 dto를 만들어 적용시키면 좋을 것 같습니다!

2024-01-24 01:43 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/schedule/service/ScheduleService.java
> +        request.scheduleDetails().stream()
해당 `scheduleDetails`를 저장하는 로직과 위의 검증 로직은 createSchedule메서드 안에서 수행하기 보단 `scheduleDetails`를 처리하는 메서드나 서비스 클래스를 따로 만들고 그걸 호출하는 방식으로 기능을 분리시키는 것이 좋을 것 같습니다!

2024-01-24 01:43 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/global/exception/ErrorCode.java
> +    FILE_READ_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "파일 읽기에 실패했습니다."),
이런 띄어쓰기 등을 일관되게 사용하기 위해선
따로 제안 주신 대로 코드 컨벤션 파일을 공통으로 사용하는 것도 좋을 것 같네요!

2024-01-24 01:43 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/schedule/dto/request/ScheduleDetailCreateRequest.java
> +        @NotBlank String scheduleDetailContent
`@NotBlank` 로 `null`과 공백을 모두 처리할 수 있네요! 
전 공백문자 처리를 생각하지 못했는데, 수정해야겠습니다. 배워가요~👍

2024-01-24 05:08 UTC, gitseoyeon approved these changes
확인했습니다~ 고생 많으셨어요!! 👍

2024-01-25 06:21 UTC, muncool39 approved these changes
메서드 분리 확인했습니다!
수고하셨어요~ 👍

2024-01-25 08:36 UTC, merged