[FEAT] 도메인 구현
Trip-Record/Server pull request #4
Opened 2024-01-06 13:24 UTC by muncool39

## Related Issue

- feat/#1 -> dev
- close #1

## Key Changes

- JpaAuditingConfig 클래스와 EntityBasicTime 으로 전역으로 사용되는 클래스를 구현
(생성 시간 자동 setting)
- cascade = CascadeType.ALL 로 부모-자식 영속성 관리
## To Reviewers

- 첫 설계대로 Record 의  CascadeType 연결을 Like 와 RecordImage 에만 했는데 Comment 에도 하는 것은 어떨까요?
- 코드에서 궁금한 점이나 변수 명 조언 등 바랍니다😀
## References

2024-01-06 15:55 UTC, ChaeAg requested changes
제 개인적인 의견으로는 `Comment` 도메인은 부모에 Cascade 설정을 하지 않아도 될 것 같습니다.
저희 서비스가 마이페이지에서 로그인한 사용자가 자신이 작성한 글이나 댓글을 한번에 확인할 수 있는 것으로 알고 있는데(확정은 아님), 삭제된 기록 게시물에 단 댓글도 확인하고 싶을 수 있겠다라는 생각이 들어서요!!

2024-01-07 04:41 UTC, gitseoyeon approved these changes
도메인이 많아서 힘드셨을텐데 고생하셨습니다!! 변수명도 명확해서 구별하기 쉬울거같아요~

2024-01-07 06:11 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/comment/Comment.java
> +    public Comment(String commentContent, Record recordId, User userId) {
확인했습니다 👍

2024-01-07 06:12 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/like/Like.java
> +@Table(name = "`like`")
맞습니다! 예약어를 테이블명으로 사용하고자 하는 경우에는 `로 감싸줘야 됩니다

2024-01-07 06:14 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/record/Record.java
> +    private Date tripEndDate;
확인했습니다 ! 👍

2024-01-07 06:16 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/user/User.java
> +    private String userName;
앗 ERD를 보면서 코드를 작성하다보니 해당 의견 반영을 깜박했네요. 
ERD를 포함해 컬럼명을 바꿔야 될 것 같습니다 👍

2024-01-07 06:28 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/basicproflie/BasicProfile.java
> +@NoArgsConstructor
JPA 에서 기본 생성자를 요구하기 때문에 명시적으로 붙였습니다.
사실 해당 코드처럼 그냥 쓸 경우에는 `@Entity` 에 포함되는 의미라 상관 없지만
`@NoArgsConstructor` 에서 access 레벨을 설정해 안정성을 높일 수 있습니다.
이번에 수정하며 protected로 기본 생성자의 접근제한을 바꿀 예정입니다😃

2024-01-07 07:27 UTC, muncool39 commented
### 변경사항
- 필드명 수정
- 매개변수명 수정
- 날짜 데이터 타입 Date -> LocalDate 변경
- 기본생성자 접근제한 설정(protected)
- `@Builder` 붙은 생성자 코드 위치 변경

2024-01-07 12:56 UTC, gitseoyeon approved these changes
확인했습니다~ 고생하셨어요!

2024-01-07 17:51 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/basicproflie/BasicProfile.java
> +@NoArgsConstructor
좋네요! 자세한 설명 감사합니다 :)

2024-01-07 17:54 UTC, ChaeAg approved these changes
도메인 설계 정말 고생 많으셨습니다!!
꼼꼼하게 잘 해주셨네요 최고입니다 👍👍

2024-01-08 03:43 UTC, merged