[FEAT] User 정보 조회 API
Trip-Record/Server pull request #40
Opened 2024-01-25 21:05 UTC by gitseoyeon

## Related Issue

- feat/#19 -> dev
- close #19

## Key Changes

마이페이지에서 유저와 관련된 정보를 보이기 위한 API 입니다.
볼 수 있는 정보는 유저의 이름과 프로필 사진, 유저의 기록 개수와 일정 개수, 유저가 받은 추천 개수(일정 + 기록), 유저가 여행간 장소의 개수 (중복X) 입니다.

처음에 기능 구현 할 때는 마이페이지에 대한 스토리보드를 받기 전이라 마이페이지에 들어갈만한 정보들을 어림잡아 생각했었는데, 스토리 보드를 본 후 보일 유저의 정보를 수정했습니다.

잠깐 이야기 나누기 전에는 회원가입 때 받은 유저 정보를 나타내는 API와 기록, 일정, 추천, 여행장소 개수의 정보를 나타내는 API를 모두 분리하여 나타냈었는데, 이야기를 나눠봤을 때 아무래도 한번의 API 호출로 원하는 값을 한번에 나타내는 게 좋다 생각하여 추후 수정 작업을 진행했습니다.

그리고 이전에 의견이 나왔던 검증 반환 및 메서드 분리도 진행해 보았습니다.

## To Reviewers

아무래도 커밋한 내용이 많다보니, 보시기에 힘들거라 생각합니다 이 점 죄송합니다 앞으로 API를 세분화 해서 PR을 올리겠습니다 😂
dto를 구현하면서 resonse와 request를 만들게 되어 따로 패키지로 구별해보았습니다. 혹시 괜찮으신지 의견 궁금합니다!
또, 뒤늦은 rebase 작업으로 충돌이 몇개 발생해서 수정 작업을 했었는데, 혹시 작업하다가 이상한 점이 있을 수도 있으니 발견하게 되신다면 리뷰 남겨 주세요!
부족한 코드라 보완할게 많을 거 같습니다..! 검토 해주시고 의견이나 질문 해 주세요!! 😊

+ 제 실수로 다시 한번 commit 을 하게 되었습니다.. 일단 그 전 파일을 백업해서 그대로 복붙하기는 했으나 혹시 이상한 부분있으면 말씁해주세요..! 그리고 똑같은 제목의 commit이 있는데 두번째거가 최신 commit입니다! 참고해주세요!

## References

2024-01-25 21:34 UTC, ChaeAg requested changes

2024-01-25 21:34 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/user/controller/dto/response/UserInfoResponse.java
> +public record UserInfoResponse(
해당 응답에는 TripStyle 이미지도 필요할 것 같아요!

2024-01-25 21:34 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/user/service/UserService.java
> +    }
유저의 기록, 일정 수는 User 엔티티가 자신과 연결된 기록, 일정 엔티티를 저장하고 있으니, 아래와 같이 구할 수 있습니다!
```java
user.getRecords().stream.count(); // 유저의 기록 수
user.getSchedules().stream.count(); // 유저의 일정 수
``` 
(하지만 현재, ,User 엔티티에 Schedules 정보를 저장하는 코드가 빠진 듯 하여, 아래 코드를 추가한 뒤 변경하셔야 할 듯합니다 ..ㅎㅎ)
```java
@OneToMany(mappedBy = "createdUser", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
private List<Schedule> schedules = new ArrayList<>();
```

2024-01-25 21:34 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/user/repository/UserRepository.java
> +    Long placeCount(@Param("user") User user);
이 부분에서 `recordLikes`, `scheduleLikes`, `placeCount` 메서드가 UserRepository에 있는 것이 적절한지에 대해 조금 의문이 듭니다
User객체를 조회하는 것이 아닌 해당 User 객체와 연관된 무엇을 조회하는 로직으로 여겨져, 각 엔티티의 레포지토리에 위치하는 것이 더 옳다고 생각이 드는데, 어떻게 생각하시나요?

2024-01-26 04:36 UTC, muncool39 requested changes
확인했습니다! 👍

2024-01-26 04:36 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/user/service/UserService.java
> +    }
@ChaeAg 
`.stream().count()`와 `Count(user)`중 `.stream().count()`가 더 좋은 이유가 있는 건가요?
궁금해서 질문드립니다!!

2024-01-26 04:36 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/user/service/UserService.java
> +        User user = getUserOrException(userId);
User 검증을 이미 위에서 했기 때문에,
count 를 구하는 각 메서드에서 반복해서 할 필요는 없을 것 같다는 생각이 듭니다!
대신 검증된 User를 넘기는 방법이 있을 것 같네요

2024-01-26 04:36 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/user/service/UserService.java
> +        return userRepository.placeCount(user);
혹시 count 되는 값이 없을 때, 수가 0으로 나올까요?
제가 예전에 구현할 때 `.orElseGet(() -> 0L)`라는 코드를 작성했던 경험이 있어서 궁금해서 질문드립니다!

2024-01-26 04:36 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/user/service/UserService.java
> +        Long likeTotal = countLikes(userId);
각 메서드 명을 count를 가져온다는 것을 나타내도록 하는건 어떨까요?
ex) `getLikeCount`

2024-01-26 04:36 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/user/controller/dto/response/UserInfoResponse.java
> +        @NotNull String userNickname,
혹시 `@NotNull` 검증이 어디에서 수행되는 걸까요?

2024-01-26 04:36 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/user/controller/dto/response/UserInfoResponse.java
> +public record UserInfoResponse(
UserInfoResponse 에 사용자의 프로필 정보와 사용자의 카운트 정보를 같이 두는 방법도 있지만
UsetProfile, UserCount (단순 예시입니다) 이런식으로 데이터를 나눈 다음 Info에 함께 넣는 방법도 있을 것 같네요!
count 정보가 아닌 user 정보는 여러 곳에서 사용될 수도 있으니까 세분화해보는 것도 좋을 것 같습니다!

2024-01-26 06:12 UTC, gitseoyeon commented on src/main/java/com/triprecord/triprecord/user/controller/dto/response/UserInfoResponse.java
> +public record UserInfoResponse(
앗! 그러네요 미처 생각하지 못하고 넣지 못했어요..! 수정하겠습니다👍

2024-01-26 06:12 UTC, gitseoyeon commented on src/main/java/com/triprecord/triprecord/user/repository/UserRepository.java
> +    Long placeCount(@Param("user") User user);
사실 저도 이 부분에 대해서 고민을 좀 해보면서 말씀 드려본 적이 있었는데, 그 당시에는 아무래도 유저의 기록, 유저의 일정이라 유저와 관련된 내용이라 생각되어 유저 레포지토리에 구현하게 되었습니다. 이 부분에 대해서는 저도 헷갈리긴하네요 ㅜㅜ

2024-01-26 06:12 UTC, gitseoyeon commented on src/main/java/com/triprecord/triprecord/user/service/UserService.java
> +        User user = getUserOrException(userId);
오! 좋은 제안 감사합니다~! 수정해보겠습니다!

2024-01-26 06:13 UTC, gitseoyeon commented on src/main/java/com/triprecord/triprecord/user/service/UserService.java
> +        return userRepository.placeCount(user);
![image](https://github.com/Trip-Record/Server/assets/126096318/c6ad87e6-1c61-4240-9af5-962781161df2)
네 테스트해본 결과 0으로 나오고 있어 따로 설정한 건 없는데 .orElseGet 메서드를 쓰면 더 안정적일까요?!

2024-01-26 06:13 UTC, gitseoyeon commented on src/main/java/com/triprecord/triprecord/user/service/UserService.java
> +        Long likeTotal = countLikes(userId);
확실히 메서드 앞에  get을 붙이면 가독성은 좋겠네요! 수정하겠습니다 👍

2024-01-26 06:13 UTC, gitseoyeon commented on src/main/java/com/triprecord/triprecord/user/controller/dto/response/UserInfoResponse.java
> +public record UserInfoResponse(
UserProfile과 UserCount 데이터를 나눈다는게 dto를 하나씩 나눠서 info dto에 함께 넣으라는 말 맞으신가요?! 생각해보니 user 정보는 말씀하신대로 여러 곳에 쓰일 수 있어 따로 하나를 만들어두면 좋긴할거같아요!

2024-01-26 06:31 UTC, gitseoyeon commented on src/main/java/com/triprecord/triprecord/user/service/UserService.java
> +    }
작성해주신 리뷰를 보고 저도 한번 알아봤는데요! respository 계층에서 쿼리문을 이용한 count 같은 경우는 stream을 사용하는 것보다 최적화 되어 있고 빠른 처리를 할 수 있다고 합니다! 그렇지만 stream 메서드 또한 비즈니스 로직을 구현하는데 있어 세밀한 작업을 할 수 있고 확장성이 높아진다고 하네요! 각각의 장단점이 존재해서 상황에 따라 구현하면 좋을듯한데 다들 어떤 방법이 괜찮으신지 의견 궁금합니다!

2024-01-26 06:43 UTC, gitseoyeon commented on src/main/java/com/triprecord/triprecord/user/controller/dto/response/UserInfoResponse.java
> +        @NotNull String userNickname,
아 제가 검증 부분을 빼놓았네요 ㅜㅜ!! 수정해서 다시 올리겠습니다!

2024-01-26 07:50 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/user/service/UserService.java
> +        return userRepository.placeCount(user);
헉 그렇군요!! 
예전에 0으로 안나와서 사용했던 기억이 있어서 혹시나 해서 질문드렸습니다!
값이 잘 나오면 변경할 필요는 없다고 생각합니다 ㅎㅎ 더 공부해볼게요!

2024-01-26 11:43 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/user/service/UserService.java
> +    }
엇 헉! 말씀 주셔서 디시 한번 고민을 해봤는데,
처음 제가 제안드렸던 이유는 이미 User 객체가 자신과 연관된 기록, 일정을 알고 있으니 다시 디비에 쿼리를 날려 연관된 자식들을 조회하여 세는 과정이 성능 상 비효율적이라고 생각했기 때문이에요..!
그런데 말씀 주셔서 다시 생각을 해보니 저희의 연관관계는 모두 지연로딩으로 조회하게 되어있어서 User가 자신과 연관된 기록, 일정 정보를 직접 참조하기 전까지는 알지 못할 것이라는 생각이 드네요..! 
그렇다면 말씀주신 것 처럼 두 방법이 크게 성능상 차이가 뚜렷하지 않을 것 같아요!
기존대로 진행하셔도 될 것 같습니다!

2024-01-26 16:13 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/user/service/UserService.java
> +    public UserInfoGetResponse findUserData(Long userId){
혹시 해당 메서드 명을 `getUserInfo` 혹은 `getUserInformation` 으로 하는 것은 어떨까요?
반환값이 `UserInfoGetResponse` 객체여서 조금 더 의미가 부드럽지 않나 하는 생각에 한 번 제안드려욧!

2024-01-26 16:16 UTC, gitseoyeon commented on src/main/java/com/triprecord/triprecord/user/service/UserService.java
> +    public UserInfoGetResponse findUserData(Long userId){
오 좋은거같아요!! 좋은 의견 감사합니다! getUserInfo로 수정하겠습니다 👍

2024-01-26 16:21 UTC, ChaeAg approved these changes
정말 고생많으셨습니다..!!!!!!!
수많은 충돌 역경들과 싸워 이기셨네요. 🎉
LGTM 👍

2024-01-26 16:39 UTC, muncool39 approved these changes
수고하셨습니다!! 👍
LGTM ..^^

2024-01-26 16:46 UTC, merged