[FEAT] 이메일 회원가입, 로그인 API 구현 완료
Trip-Record/Server pull request #5
Opened 2024-01-09 16:12 UTC by ChaeAg

## Related Issue

- feat/#2 -> dev
- close #2

## Key Changes

회원가입 시 받는 정보는 다음과 같습니다.
1. userEmail
2. userPassword
3. userNickname
4. userAge (생년월일)
5. userBasicProfileId
6. userTripStyleId

도메인명 `userNickName` -> `userNickname` 으로 변경했습니다.

## To Reviewers

부족한 점이나 개선사항, 궁금한 점이 있다면 바로 말씀해주세요!!

## References

2024-01-10 08:15 UTC, muncool39 requested changes
어려운 내용이라고 생각하는데 너무 잘하신 것 같습니다....
Request가 지금은 두개지만 늘어남에 따라 하위 패키지로 분리해도 좋을 것 같네요!

2024-01-10 08:15 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/global/config/jwt/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader(HttpHeaders.AUTHORIZATION);
여기서 getHeader로 가져오는 것은 header고 bearerToken이 들어있는지는 뒤에서 판단하니
변수명을 수정하는 것은 어떨까요? ex) `header`

2024-01-10 08:15 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/global/config/jwt/JwtProvider.java
> +    private static final Long TOKEN_EXPIRATION_TIME = 24 * 60 * 60 * 1000L; // 24시간
만료시간도 따로 설정해 `@Value`로 가져오는 것은 어떨까요?
ex)
```java
@Value("${jwt.token.expired-time}")
```

2024-01-10 08:15 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/user/UserService.java
> +    public String signup(UserCreateRequest userCreateRequest) throws AuthException {
`throws AuthException` 가 어떻게 적용되는지 알 수 있을까요?

2024-01-10 08:15 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/user/UserController.java
> +            URI uri = URI.create("/users/" + userService.signup(userCreateRequest));
회원가입 후 왜 해당 URI를 생성하는지 알 수 있을까요?

2024-01-10 08:15 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/user/UserService.java
> +                .userPassword(userCreateRequest.userPassword())
보안 강화를 위해 `userPassword` 를 `BCryptPasswordEncoder`로 암호화해 저장하는건 어떨까요?

2024-01-10 08:15 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/user/UserCreateRequest.java
> +public record UserCreateRequest(
record를 처음 봐서 찾아봤는데 좋네요 👍
DTO의 역할 수행에 딱이군요!

2024-01-10 08:15 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/global/config/jwt/JwtProvider.java
> +        return Keys.hmacShaKeyFor(encodedKey.getBytes());   //일반적으로 HMAC (Hash-based Message Authentication Code) 알고리즘 사용
`JWT_SECRET`의 암호화한 byte값을 String으로 변환하지 않고 byte[] 로 받는 것은 어떨까요?
ex)
```java
byte[] encodedKeyBytes = Base64.getEncoder().encode(JWT_SECRET.getBytes(StandardCharsets.UTF_8));
return Keys.hmacShaKeyFor(encodedKeyBytes);
```
아니면 String으로 변환한 이유가 따로 있을까요?

2024-01-10 08:15 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/global/config/jwt/JwtProvider.java
> +    public Long getUserFromJwt(String token) {
반환값이 User 객체가 아닌 User의 Id이기 때문에
메소드명을 `getUserIdFromJwt` 로 수정하는 것은 어떨까요?

2024-01-10 08:15 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/global/config/jwt/JwtProvider.java
> +                .signWith(getSigningKey()) // Signature
혹시 signWith 에 `SignatureAlgorithm.HS256` 을 작성하지 않은 이유가 있을까요?

2024-01-10 08:15 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/global/config/jwt/JwtProvider.java
> +        JWT_SECRET = Base64.getEncoder().encodeToString(JWT_SECRET.getBytes(StandardCharsets.UTF_8));
밑 getSigningKey에도 동일한 암호화 과정이 있어서
이 과정을 따로 수행하는 이유가 궁금합니다!

2024-01-10 08:15 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/user/UserController.java
> +            return ResponseEntity.ok().body(Map.of("Authorization", userService.login(userLoginRequest))); // 토큰 body에 담아서 보냄
service에서 얻는 토큰을 변수로 받고난 다음 Map을 해주는 건 어떨까요?
주석에 설명이 있긴 하지만 받는 것이 token인걸 확실히 명시하는게 더 좋을 것 같다는 생각이 들어서요!
ex)
```java
String token = userService.login(userLoginRequest);
return ResponseEntity.ok().body(Map.of("Authorization", token));
```

2024-01-10 08:15 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/user/UserController.java
> +            return ResponseEntity.badRequest().body(e.getMessage());
해당 에러 처리를 `@RestControllerAdvice`와 `@ExceptionHandler` 를 활용해 전역 처리해보는 건 어떨까요?
(이 부분은 따로 담당자를 정해 개발을 진행해도 좋을 것 같네요!)

2024-01-10 08:15 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/global/config/SecurityConfig.java
> +            }
혹시 해당 cors 설정은 서버가 확정됨에 따라 수정될 가능성이 있는지 궁금합니다!

2024-01-10 08:15 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/user/UserController.java
> +            return ResponseEntity.ok().body(Map.of("Authorization", userService.login(userLoginRequest))); // 토큰 body에 담아서 보냄
token 필드를 갖는 UserResponse 를 생성해서 해당 객체에 담는 방법도 있을 것 같네요!
혹시 이 부분에 대해서는 어떻게 생각하시나요?

2024-01-10 09:15 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/global/config/jwt/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader(HttpHeaders.AUTHORIZATION);
좋은 생각이네요!
수정하겠습니다!

2024-01-10 09:15 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/global/config/jwt/JwtProvider.java
> +    private static final Long TOKEN_EXPIRATION_TIME = 24 * 60 * 60 * 1000L; // 24시간
오 좋습니다!!
수정하도록 할게요~!

2024-01-10 09:15 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/global/config/jwt/JwtProvider.java
> +        JWT_SECRET = Base64.getEncoder().encodeToString(JWT_SECRET.getBytes(StandardCharsets.UTF_8));
저도 배울 때 그냥 이렇게 하라고 배웠는데, 리뷰 보고 급하게 알아봤는데, 수정이 필요한 부분인 것 같아요..! 수정해서 다시 pr 요청하겠습니다!

2024-01-10 09:15 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/global/config/jwt/JwtProvider.java
> +                .signWith(getSigningKey()) // Signature
이 부분도 제가 놓쳤네요..!!
수정하겠습니다~

2024-01-10 09:15 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/global/config/jwt/JwtProvider.java
> +        return Keys.hmacShaKeyFor(encodedKey.getBytes());   //일반적으로 HMAC (Hash-based Message Authentication Code) 알고리즘 사용
저는 배울 때 String 으로 변환해야 한다고 배웠는데 ,, 알아보니 아니더라구요.
수정하겠습니다!

2024-01-10 09:15 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/global/config/jwt/JwtProvider.java
> +    public Long getUserFromJwt(String token) {
오 좋습니다!
반영하겠습니다~!

2024-01-10 09:15 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/user/UserController.java
> +            URI uri = URI.create("/users/" + userService.signup(userCreateRequest));
URI를 생성하는 이유는 HTTP 응답 코드를 201 created로 내려주기 위함입니다!
ResponseEntity.created() 에는 URI값이 필요하더라구요!

2024-01-10 09:15 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/user/UserController.java
> +            return ResponseEntity.ok().body(Map.of("Authorization", userService.login(userLoginRequest))); // 토큰 body에 담아서 보냄
넵 좋은 생각이네요!
반영할게요~

2024-01-10 09:15 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/user/UserController.java
> +            return ResponseEntity.ok().body(Map.of("Authorization", userService.login(userLoginRequest))); // 토큰 body에 담아서 보냄
저도 고민을 했는데, 딱 이 부분에서만 사용하기 때문에 단순히 Map으로 생성해줬습니다..! 
너무 보기에 깔끔하지 않을까요?

2024-01-10 09:15 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/user/UserController.java
> +            return ResponseEntity.badRequest().body(e.getMessage());
앗 전역 에러 처리는 한 번 해보고 싶었던 기술인데, 아직 제가 학습을 더 해야하는 부분이라 일단 try-catch문으로 처리했습니다!
이 부분은 나중에 제가 더 학습을 해서 리팩토링 하도록 하겠습니다!

2024-01-10 09:15 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/user/UserCreateRequest.java
> +public record UserCreateRequest(
네 record가 DTO를 위해 나온 클래스 유형이라고 해요!

2024-01-10 09:15 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/user/UserService.java
> +    public String signup(UserCreateRequest userCreateRequest) throws AuthException {
앗 회원가입 로직에서는 해당 익셉션이 필요하지 않네요! 
좋은 지적 감사합니다!

2024-01-10 09:15 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/user/UserService.java
> +                .userPassword(userCreateRequest.userPassword())
앗 네! 
해당 부분을 빼먹었네요 ㅎㅎ 추가하겠습니다!

2024-01-10 09:17 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/global/config/SecurityConfig.java
> +            }
네 이 부분은 현재는 다 열어줬지만, 추후에는 저희가 허락한 경로만 들어올 수 있도록 수정해야할 것 같아요!

2024-01-10 11:33 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/user/UserController.java
> +            URI uri = URI.create("/users/" + userService.signup(userCreateRequest));
좋네요! 새롭게 알아갑니다 👍

2024-01-10 17:12 UTC, gitseoyeon requested changes
짧은 시간에 많이 구현하시느라 고생하셨습니다!! 몇 가지 수정하셔야 할것만 수정하시면 좋을거같아요!!

2024-01-11 01:28 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/user/UserCreateRequest.java
> +        Long userTripStyleId
Service에서 해당 request 데이터에 null이 들어가는 경우에 대한 예외처리가 없는 걸로 보이는데
JwtAuthenticationFilter 클래스의 doFilterInternal 메소드의 매개변수에 사용한 것처럼
`@NonNull` 이나 `@NotNull`을 적용할 수 있을까요?

2024-01-11 11:03 UTC, gitseoyeon approved these changes
수정 내용 잘 봤습니다~ 고생하셨어요!

2024-01-11 11:14 UTC, gitseoyeon approved these changes
넵 확인했습니다!

2024-01-11 11:14 UTC, muncool39 approved these changes
리뷰 받은 내용을 꼼꼼히 수정하신 것 같아요 👍
수고하셨습니다!

2024-01-11 11:17 UTC, merged