[FEAT] 여행지 장소 조회 API
Trip-Record/Server pull request #60
Opened 2024-01-31 12:55 UTC by gitseoyeon

## Related Issue

- feat/#56 -> dev
- close #56

## Key Changes

유저가 기록이나 일정을 기록 할 때 여행 장소를 선택하기 위해 데이터를 불러오는 API 입니다.
LocationInfoResponse에 대륙명과 PlaceBasicData(나라명, 지역명) dto를 리스트로 넣어 만들었습니다.
## To Reviewers

여행 지역에 대한 모든 정보를 불러오는 것이기 때문에 LocationController를 하나 만들었습니다. 하지만 service 는 PlaceService에 구현하였기 때문에 그냥 PlaceController에 구현하는 것이 맞는지 고민이 됩니다! 의견 있으시면 말씀해주세요!
현재 DB에 대륙명중 아시아/증동으로 오타가 난 것이 있는데, 중동으로 바로 수정하겠습니다. 현재 오타는 감안하고 봐주세요..!
![image](https://github.com/Trip-Record/Server/assets/126096318/9075af2b-e983-402c-9540-48bb4a422532)
![image](https://github.com/Trip-Record/Server/assets/126096318/8b55756d-df87-4b92-91ab-b87948e6cac9)

## References

2024-01-31 13:21 UTC, muncool39 requested changes
확인했습니다! 👍
Controller는 연관성이 높은 정보들이기 때문에 PlaceController 로 통합해서 사용해도 나쁘진 않을 것 같습니다!
아니면 이번에 만드신 것처럼 패키지명인 LocationController 로 통합해도 좋을 것 같네요!

2024-01-31 13:21 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/location/controller/LocationController.java
> +        return ResponseEntity.ok().body(placeService.getLocationInfo());
이전에 맞춰온것처럼 ok 도 status로 명시해주는게 좋을 것 같습니다!

2024-01-31 13:21 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/location/repository/PlaceRepository.java
> +    List<Place> findPlaceByPlaceCountry(Country country);
조건에 맞는 모든 Place를 찾는 것이니 메서드명을 findAllPlace~ 로 해도 좋을 것 같습니다!

2024-01-31 13:24 UTC, gitseoyeon commented on src/main/java/com/triprecord/triprecord/location/controller/LocationController.java
> +        return ResponseEntity.ok().body(placeService.getLocationInfo());
엇.. 제가 습관처럼 저렇게 작성했네요..! 바로 수정하겠습니다 😂

2024-01-31 13:25 UTC, gitseoyeon commented on src/main/java/com/triprecord/triprecord/location/repository/PlaceRepository.java
> +    List<Place> findPlaceByPlaceCountry(Country country);
오 그것도 좋을거 같아요!

2024-01-31 13:30 UTC, gitseoyeon commented on src/main/java/com/triprecord/triprecord/location/repository/PlaceRepository.java
> +    List<Place> findPlaceByPlaceCountry(Country country);
조건이 country니까 findAllByPlaceCountry는 어떤가요?!

2024-01-31 13:39 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/location/repository/PlaceRepository.java
> +    List<Place> findPlaceByPlaceCountry(Country country);
전 좋습니다~~👍

2024-02-01 02:14 UTC, muncool39 approved these changes
수정 확인했습니다 ! 👍

2024-02-02 22:37 UTC, ChaeAg approved these changes
고생하셨습니다! 코멘트 한 번 봐주시면 감사하겠습니다~!~!

2024-02-02 22:37 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/location/repository/ContinentRepository.java
> +    List<Continent> findAll();
이러한 findAll() 메서드는 JPA에서 제공을 해줘서 선언하지 않아도 사용이 가능합니다!

2024-02-02 22:37 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/location/repository/CountryRepository.java
> +    List<Country> findCountryByContinent(Continent continent);
PlaceRepository 내 `List<Place> findAllByPlaceCountry` 메서드처럼 해당 메서드도 CountryRepository에서 수행되어 이미 Country 객체를 조회하는 것이 명시되어 있기에, 메서드 명을 `List<Country> findAllByContinent`로 변경하는 것은 어떨까요?

2024-02-03 18:24 UTC, gitseoyeon commented on src/main/java/com/triprecord/triprecord/location/repository/ContinentRepository.java
> +    List<Continent> findAll();
헉 그렇군요!! 나중에 따로 수정 해서 올리겠습니다!

2024-02-03 18:26 UTC, gitseoyeon commented on src/main/java/com/triprecord/triprecord/location/repository/CountryRepository.java
> +    List<Country> findCountryByContinent(Continent continent);
오 그러네요! 좋은 의견인 거 같습니다 수정해서 머지 하겠습니다!

2024-02-03 18:35 UTC, merged