[FEAT] 월별 랭킹 조회 API
Trip-Record/Server pull request #63
Opened 2024-02-03 18:23 UTC by gitseoyeon

## Related Issue

- feat/#61 -> dev
- close #61

## Key Changes

rank 정보를 담고 있는 dto를 만들어서 placeBasicData로 장소 정보를 담고, visitCount로 방문 횟수와 rank로 방문 횟수에 따른 랭크 정보를 갖을 수 있게 했습니다.
기록의 start_date를 기준으로 한 월별 랭킹 정보이며, 방문 횟수가 많은 상위 7개의 장소를 리턴하게 구현했습니다.
![image](https://github.com/Trip-Record/Server/assets/126096318/bbb6185a-e8cc-463e-a1ca-23e4b2d83ccc)
![image](https://github.com/Trip-Record/Server/assets/126096318/cd3f0d40-6a56-4e97-a282-d730848fedea)
![image](https://github.com/Trip-Record/Server/assets/126096318/5afb5014-d47e-4283-b3f6-c15d5e5c6945)

## To Reviewers

api 의 엔드포인트가 ranks로 시작한다는 점에서 rankController를 따로 생성했는데, 아무래도 record의 정보를 가지고 랭킹을 구하는 것이다 보니 서비스 구현은 recordService에 했습니다. 따로 rankService를 만들어서 구현해야 할 지, recordPlace를 기준으로 랭킹을 집계하는 것이기 때문에 recordPlaceService에 구현 해야 할 지, 그대로 둘 지 고민입니다! 
그리고 아무래도 rank 쿼리를 구현하기 위해서는 nativeQuery를 사용 할 수밖에 없어서 다소 복잡해 보이긴 하는데 혹시 다른 방법 아시는 분은 리뷰 남겨주세요~
이 외에도 질문이나 의견 있으시면 편하게 말씀해주세요!

## References

2024-02-04 07:27 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/record/service/RecordService.java
> +        }
해당 반복문에서 visitCount와 Place를 Map에 저장하여 visitCount 기준 내림차순으로 정렬한 뒤 맨 앞에서부터 7번째 값까지 가져오는 식으로 랭킹을 구하는 방식은 어떨까요?

2024-02-04 07:27 UTC, ChaeAg commented on src/main/java/com/triprecord/triprecord/record/service/RecordService.java
> +            Integer rank = recordPlaceRepository.getRank(place.getPlaceId(),date).orElseGet(() -> 0);
혹시 visitCount와 rank는 Integer로 사용하는 이유가 있나용?
제가 잘 몰라서욧,.,!

2024-02-04 10:42 UTC, gitseoyeon commented on src/main/java/com/triprecord/triprecord/record/service/RecordService.java
> +        }
아 map을 사용하는 방법도 있긴 하겠네요! map을 사용하면 속도면에서 더 빠른건가요?!

2024-02-04 10:44 UTC, gitseoyeon commented on src/main/java/com/triprecord/triprecord/record/service/RecordService.java
> +            Integer rank = recordPlaceRepository.getRank(place.getPlaceId(),date).orElseGet(() -> 0);
제가 예전에 다른 프로젝트를 진행할 때도 rank를 구하는 api를 작성한적이 있었는데요! int값으로 하면 레포지토리에서 쿼리문 작성하고 값을 구할 때 값이 안들어가는 에러가 발생한 적이 있어 Integer를 사용하고 있습니다!

2024-02-04 13:01 UTC, muncool39 requested changes
확인했습니다 !👍
장소의 랭킹이니 PlaceService에 구현하는 것도 좋은 방법인 것 같아요!
확실히 쿼리문이 복잡해지는데, 저도 개선 방법을 생각해보겠습니다!

2024-02-04 13:01 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/record/controller/response/RecordPlaceRankGetResponse.java
> +public record RecordPlaceRankGetResponse(
클래스명에 GET이라는 행위를 생략해도 괜찮지 않을까요? 그냥 의견입니다!!

2024-02-04 13:01 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/record/service/RecordService.java
> +        }
아니면 TreeMap을 사용해 정렬 과정을 생략하는 방법도 있겠네요!

2024-02-04 14:05 UTC, gitseoyeon commented on src/main/java/com/triprecord/triprecord/record/service/RecordService.java
> +        }
한번 시도해보고 다시 커밋 올려보겠습니다!

2024-02-04 14:16 UTC, gitseoyeon commented on src/main/java/com/triprecord/triprecord/record/controller/response/RecordPlaceRankGetResponse.java
> +public record RecordPlaceRankGetResponse(
앗 user와 schedule 쪽 response가 get이 붙어 있어서 통일성을 주고자 넣었었는데 혹시 get을 안 넣는게 더 보기가 좋으려나요?

2024-02-04 15:27 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/record/controller/response/RecordPlaceRankGetResponse.java
> +public record RecordPlaceRankGetResponse(
헉 일단 제쪽에서는 Response DTO에 get을 붙이지 않았습니다! 
Response 자체가 무조건 클라이언트 쪽에서 Get하는 데이터라 백엔드에서 굳이 붙여야 될까 생각이 들었어요 !
단순 의견이라 취향껏 하셔도 될 것 같긴 합니다! ㅎ.ㅎ

2024-02-04 16:23 UTC, gitseoyeon commented on src/main/java/com/triprecord/triprecord/record/controller/response/RecordPlaceRankGetResponse.java
> +public record RecordPlaceRankGetResponse(
아아 그러면 이 점에 대해서는 나중에 회의를 통해서 클래스명 형식을 통일해도 좋을거같네요!

2024-02-04 16:56 UTC, gitseoyeon commented on src/main/java/com/triprecord/triprecord/record/service/RecordService.java
> +        }
말씀해주신 대로 TreeMap을 활용해서 rank를 구하는 방식을 시도해 봤는데요! 구현하면서 생각해보니 지역별로 방문한 횟수가 같을 경우 지금 상태로는 rank 쿼리문을 통해 공동 순위를 주고 있는데 map을 사용한다면 이 점이 구현하는데 어려울 거 같은데 혹시 방법이 있을까요..?

2024-02-05 14:07 UTC, muncool39 approved these changes
확인했습니다! 랭킹 관련해서는 저도 더 공부해볼게요 ㅎㅎ
수고하셨습니다~

2024-02-05 14:43 UTC, ChaeAg approved these changes
수고하셨습니다 ㅎㅎ
LGTM~~ 👍

2024-02-05 14:47 UTC, merged