[FEAT] 일정 댓글 생성 API
Trip-Record/Server pull request #77
Opened 2024-02-07 16:14 UTC by ChaeAg

## Related Issue

- feat/#76 -> dev
- close #76

## Key Changes

### 일정 댓글 생성 API
로그인한 사용자 정보와, 일정 ID, 댓글 내용을 받아 댓글을 생성하는 API

댓글 내용은 null, 빈 문자열을 허용하지 않습니다.

기존 엔티티 설계 시 생성된 시간을 저장하는 EntityBaseTime 클래스를 상속 받도록 설계해두었기에, 일정 댓글 생성 시 생성된 시간이 함께 DB에 저장됩니다.

## To Reviewers

X

## References

X

2024-02-08 07:32 UTC, gitseoyeon approved these changes
확인했습니다! 고생하셨어요!

2024-02-08 10:44 UTC, muncool39 approved these changes
확인했습니다! 수고하셨어요 👍

2024-02-08 10:46 UTC, muncool39 requested changes

2024-02-08 10:46 UTC, muncool39 commented on src/main/java/com/triprecord/triprecord/schedule/controller/ScheduleController.java
> +                .status(HttpStatus.OK)
앗!! 이 부분의 HttpStatus는 create로 바꾸는 것은 어떨까요?

2024-02-09 10:56 UTC, muncool39 approved these changes
변경 확인했습니다 ! 수고하셨어요! 👍

2024-02-09 15:38 UTC, merged